In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r'dataset.csv')
df.head()

Unnamed: 0  Unnamed: 1             Unnamed: 2             Unnamed: 3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

             Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0   dischromic _patches        NaN        NaN        NaN        NaN   
1                   NaN        NaN        NaN        NaN        NaN   
2                   NaN        NaN        NaN        NaN        NaN   
3                   NaN        NaN        NaN        NaN        NaN   
4                   NaN        NaN        NaN        NaN        NaN   

  Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14  \
0        NaN         NaN         NaN         NaN         NaN         NaN   
1        NaN         NaN         NaN         NaN         NaN         NaN   
2        NaN         NaN         NaN         NaN         NaN         NaN   
3        NaN         NaN         NaN         NaN         NaN         NaN   
4        NaN         NaN         NaN         NaN         NaN         NaN   

  Unnamed: 15 Unnamed: 16 Unnamed: 17  
0         NaN         NaN         NaN  
1         NaN         NaN         NaN  
2         NaN         NaN         NaN  
3         NaN         NaN         NaN  
4         NaN         NaN         NaN

In [3]:
df.isnull().sum()

Unnamed: 0        0
Unnamed: 1        0
Unnamed: 2        0
Unnamed: 3        0
Unnamed: 4      348
Unnamed: 5     1206
Unnamed: 6     1986
Unnamed: 7     2652
Unnamed: 8     2976
Unnamed: 9     3228
Unnamed: 10    3408
Unnamed: 11    3726
Unnamed: 12    4176
Unnamed: 13    4416
Unnamed: 14    4614
Unnamed: 15    4680
Unnamed: 16    4728
Unnamed: 17    4848
dtype: int64

In [4]:
# Define the new column names
new_column_names = [
    "Disease", 
    "Symptom_1", "Symptom_2", "Symptom_3", "Symptom_4", 
    "Symptom_5", "Symptom_6", "Symptom_7", "Symptom_8", 
    "Symptom_9", "Symptom_10", "Symptom_11", "Symptom_12", 
    "Symptom_13", "Symptom_14", "Symptom_15", "Symptom_16", 
    "Symptom_17"
]

# Rename the columns in the DataFrame
df.columns = new_column_names

# Print the column-wise missing value counts
print(df.isnull().sum())


Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64


In [5]:
df.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [6]:
df

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                        NaN   
2      nodal_skin_eruptions    dischromic _patches                        NaN   
3                 skin_rash    dischromic _patches                        NaN   
4                 skin_rash   nodal_skin_eruptions                        NaN   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                       NaN                  NaN       NaN       NaN   
1                       NaN                  NaN       NaN       NaN   
2                       NaN                  NaN       NaN       NaN   
3                       NaN                  NaN       NaN       NaN   
4                       NaN                  NaN       NaN       NaN   
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness       NaN       NaN   
4916                    NaN                  NaN       NaN       NaN   
4917                    NaN                  NaN       NaN       NaN   
4918   small_dents_in_nails   inflammatory_nails       NaN       NaN   
4919      yellow_crust_ooze                  NaN       NaN       NaN   

     Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0          NaN        NaN        NaN        NaN        NaN        NaN   
1          NaN        NaN        NaN        NaN        NaN        NaN   
2          NaN        NaN        NaN        NaN        NaN        NaN   
3          NaN        NaN        NaN        NaN        NaN        NaN   
4          NaN        NaN        NaN        NaN        NaN        NaN   
...        ...        ...        ...        ...        ...        ...   
4915       NaN        NaN        NaN        NaN        NaN        NaN   
4916       NaN        NaN        NaN        NaN        NaN        NaN   
4917       NaN        NaN        NaN        NaN        NaN        NaN   
4918       NaN        NaN        NaN        NaN        NaN        NaN   
4919       NaN        NaN        NaN        NaN        NaN        NaN   

     Symptom_15 Symptom_16 Symptom_17  
0           NaN        NaN        NaN  
1           NaN        NaN        NaN  
2           NaN        NaN        NaN  
3           NaN        NaN        NaN  
4           NaN        NaN        NaN  
...         ...        ...        ...  
4915        NaN        NaN        NaN  
4916        NaN        NaN        NaN  
4917        NaN        NaN        NaN  
4918        NaN        NaN        NaN  
4919        NaN        NaN    

In [7]:
df.to_csv('corrected_dataset.csv', index=False)

In [8]:
df = df.fillna("")
df['Symptom']=""
for i in range(1,18):
    df['s']=df["Symptom_{}".format(i)]
    df['Symptom']=df['Symptom']+df['s']

In [9]:
df

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                              
2      nodal_skin_eruptions    dischromic _patches                              
3                 skin_rash    dischromic _patches                              
4                 skin_rash   nodal_skin_eruptions                              
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                                                                      
1                                                                      
2                                                                      
3                                                                      
4                                                                      
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness                       
4916                                                                   
4917                                                                   
4918   small_dents_in_nails   inflammatory_nails                       
4919      yellow_crust_ooze                                            

     Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0                                                                       
1                                                                       
2                                                                       
3                                                                       
4                                                                       
...        ...        ...        ...        ...        ...        ...   
4915                                                                    
4916                                                                    
4917                                                                    
4918                                                                    
4919                                                                    

     Symptom_15 Symptom_16 Symptom_17  \
0                                       
1                                       
2                                       
3                                       
4                                       
...         ...        ...        ...   
4915                                    
4916                                    
4917                                    
4918                                    
4919               

In [10]:
for i in range(1,18):
    df=df.drop("Symptom_{}".format(i),axis=1)
df=df.drop("s",axis=1)

In [11]:
df.head()

Disease                                            Symptom
0  Fungal infection  itching skin_rash nodal_skin_eruptions dischro...
1  Fungal infection   skin_rash nodal_skin_eruptions dischromic _pa...
2  Fungal infection   itching nodal_skin_eruptions dischromic _patches
3  Fungal infection              itching skin_rash dischromic _patches
4  Fungal infection             itching skin_rash nodal_skin_eruptions

In [12]:
df[0:1].values

array([['Fungal infection',
        'itching skin_rash nodal_skin_eruptions dischromic _patches']],
      dtype=object)

In [13]:
df['Disease'].value_counts()

Disease
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
Aller

In [14]:
X=df['Symptom']
y=df['Disease']

In [15]:
X.head(10)

0    itching skin_rash nodal_skin_eruptions dischro...
1     skin_rash nodal_skin_eruptions dischromic _pa...
2     itching nodal_skin_eruptions dischromic _patches
3                itching skin_rash dischromic _patches
4               itching skin_rash nodal_skin_eruptions
5     skin_rash nodal_skin_eruptions dischromic _pa...
6     itching nodal_skin_eruptions dischromic _patches
7                itching skin_rash dischromic _patches
8               itching skin_rash nodal_skin_eruptions
9    itching skin_rash nodal_skin_eruptions dischro...
Name: Symptom, dtype: object

In [16]:
y.head(10)

0    Fungal infection
1    Fungal infection
2    Fungal infection
3    Fungal infection
4    Fungal infection
5    Fungal infection
6    Fungal infection
7    Fungal infection
8    Fungal infection
9    Fungal infection
Name: Disease, dtype: object

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,shuffle=True,random_state=44)

In [18]:
y_train.head(10)

1057        Hepatitis E
4480           Migraine
2394    Osteoarthristis
4467          Psoriasis
3525           Impetigo
3038      Drug Reaction
4906          Pneumonia
4131     Hypothyroidism
1405             Dengue
3033           Impetigo
Name: Disease, dtype: object

In [19]:
print('Training Data Shape:', X_train.shape)
print('Testing Data Shape: ', X_test.shape)

Training Data Shape: (3690,)
Testing Data Shape:  (1230,)


In [20]:
y_train.value_counts()

Disease
Jaundice                                   98
Migraine                                   98
hepatitis A                                95
Heart attack                               95
Dimorphic hemmorhoids(piles)               95
Allergy                                    95
Hepatitis C                                93
Hepatitis D                                93
Typhoid                                    92
Gastroenteritis                            92
Pneumonia                                  92
Hypoglycemia                               92
Common Cold                                91
Tuberculosis                               91
Fungal infection                           91
Hepatitis E                                91
Arthritis                                  91
Psoriasis                                  91
Peptic ulcer diseae                        91
Malaria                                    90
Bronchial Asthma                           90
Dengue                    

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train)
X_train_tfidf.shape

(3690, 135)

In [22]:
pd.DataFrame(X_train_tfidf)[0]

0       <Compressed Sparse Row sparse matrix of dtype ...
1       <Compressed Sparse Row sparse matrix of dtype ...
2       <Compressed Sparse Row sparse matrix of dtype ...
3       <Compressed Sparse Row sparse matrix of dtype ...
4       <Compressed Sparse Row sparse matrix of dtype ...
                              ...                        
3685    <Compressed Sparse Row sparse matrix of dtype ...
3686    <Compressed Sparse Row sparse matrix of dtype ...
3687    <Compressed Sparse Row sparse matrix of dtype ...
3688    <Compressed Sparse Row sparse matrix of dtype ...
3689    <Compressed Sparse Row sparse matrix of dtype ...
Name: 0, Length: 3690, dtype: object

In [23]:
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(X_train_tfidf,y_train)

LinearSVC()

In [24]:
from sklearn.pipeline import Pipeline
text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),])


text_clf.fit(X_train, y_train)  


predictions = text_clf.predict(X_test)

In [25]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[33  0  0 ...  0  0  0]
 [ 0 33  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 31  0  0]
 [ 0  0  0 ...  0 31  0]
 [ 0  0  0 ...  0  0 25]]


In [26]:
print(metrics.classification_report(y_test,predictions))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        33
                                   AIDS       1.00      1.00      1.00        33
                                   Acne       1.00      1.00      1.00        35
                    Alcoholic hepatitis       1.00      1.00      1.00        33
                                Allergy       1.00      1.00      1.00        25
                              Arthritis       1.00      1.00      1.00        29
                       Bronchial Asthma       1.00      1.00      1.00        30
                   Cervical spondylosis       1.00      1.00      1.00        35
                            Chicken pox       1.00      1.00      1.00        35
                    Chronic cholestasis       1.00      1.00      1.00        31
                            Common Cold       1.00      1.00      1.00        29
                           

In [27]:
print(metrics.accuracy_score(y_test,predictions))

1.0


In [28]:
import numpy as np
import pandas as pd

In [29]:
df

Disease  \
0                            Fungal infection   
1                            Fungal infection   
2                            Fungal infection   
3                            Fungal infection   
4                            Fungal infection   
...                                       ...   
4915  (vertigo) Paroymsal  Positional Vertigo   
4916                                     Acne   
4917                  Urinary tract infection   
4918                                Psoriasis   
4919                                 Impetigo   

                                                Symptom  
0     itching skin_rash nodal_skin_eruptions dischro...  
1      skin_rash nodal_skin_eruptions dischromic _pa...  
2      itching nodal_skin_eruptions dischromic _patches  
3                 itching skin_rash dischromic _patches  
4                itching skin_rash nodal_skin_eruptions  
...                                                 ...  
4915   vomiting headache nausea spinning_movements l...  
4916   skin_rash pus_filled_pimples blackheads scurring  
4917   burning_micturition bladder_discomfort foul_s...  
4918   skin_rash joint_pain skin_peeling silver_like...  
4919   skin_rash high_fever blister red_sore_around_...  

[4920 rows x 2 columns]

In [ ]:
import pandas as pd

# Column names as provided
column_names = [
    "Disease", 
    "Symptom_1", "Symptom_2", "Symptom_3", "Symptom_4", 
    "Symptom_5", "Symptom_6", "Symptom_7", "Symptom_8", 
    "Symptom_9", "Symptom_10", "Symptom_11", "Symptom_12", 
    "Symptom_13", "Symptom_14", "Symptom_15", "Symptom_16", 
    "Symptom_17"
]

# Step 1: Load the dataset
df = pd.read_csv('corrected_dataset.csv', names=column_names)

# Step 2: Initialize empty DataFrame for symptoms
symptoms_df = pd.DataFrame(index=df.index)

# Step 3: Process each row to create symptom columns
unique_symptoms = set()
for i in range(1, 18):
    unique_symptoms.update(df[f'Symptom_{i}'].dropna().unique())

# Remove any empty strings or invalid values
unique_symptoms = {symptom for symptom in unique_symptoms if isinstance(symptom, str) and symptom.strip()}

# Create a column for each symptom
for symptom in unique_symptoms:
    # Initialize the column with zeros
    symptoms_df[symptom] = 0
    # Check each symptom column for this symptom
    for i in range(1, 18):
        symptoms_df[symptom] = symptoms_df[symptom] | (df[f'Symptom_{i}'] == symptom)

# Convert to int type
symptoms_df = symptoms_df.astype(int)

# Keep the original Disease column
symptoms_df['Disease'] = df['Disease']

# Reorder columns to have Disease first
cols = ['Disease'] + [col for col in symptoms_df.columns if col != 'Disease']
symptoms_df = symptoms_df[cols]

# Print some information
print("Shape of encoded DataFrame:", symptoms_df.shape)
print("\nColumns in the DataFrame:")
print(symptoms_df.columns.tolist())
print("\nFirst few rows:")
print(symptoms_df.head())

# Save the encoded DataFrame
symptoms_df.to_csv('training.csv', index=False)

# Print number of unique symptoms
print(f"\nNumber of unique symptoms: {len(unique_symptoms)}")